### PR TITLE
Fix for proper cloning of project's Git repo without the Drupal path …

### PR DESCRIPTION
**Pull request by moerazem**
When cloning a new project, Git tries to clone to the Drupal path. Resulting in a an error "We could not find an applicable site for that command. Drush could not bootstrap this platform. Please check the platform directory exists and is readable."

That is because the git clone command will use the platform path as a git clone path. This is wrong, it should clone to the environment path without the Drupal path.

This fixes it.

### CODE REVIEW

**Comment by moerazem** [comment]
The build fail was due to something else.

**Comment by jonpugh** [comment]
Sorry about the delay in reviewing this.

I have a big PR out that has too many things in it, one of which is a move to use hosting_git to store all of this, so "drupal_path" is going away in favor of platform->repo_path.

However in the name of getting it working I'm going to merge this once that test passes and I can manually confirm it's working...

Tomorrow when I can sanity check myself

**Comment by jonpugh** [comment]
I am adding a repo with drupal in a docroot to the tests. Once that's merged, it will confirm that this works, and I'll merge.

**Comment by jonpugh** [comment]
Ok, I figured out what happened.  A number of commits converting to the use of hosting_git made it into the 1.x branch.  This was an accident. The rest of the work was done in another branch.

I've pulled all of those commits into a new PR: https://github.com/opendevshop/devmaster/pull/57 and am adding the new tests there.

**Comment by jonpugh** [comment]
Projects with drupal in docroot folder are now being tested: https://github.com/opendevshop/devmaster/pull/61

**Pull request closed without merging**
