### PR TITLE
modified project git url to obfuscate password if it exists

### PR DESCRIPTION
**Pull request by llwp**
this does not change the db value, but if conditions exist such that a password is saved... presents in the UI without the password revealed...

### CODE REVIEW

**Comment by jonpugh** [comment]
Thanks for the work... It's almost there. 

Remember, `git_repo_url` is a HTTP interpretation of the `git_repo`, usually used to transform git@github.com to http://github.com.  use `git_repo` when trying to access the actual stored git origin.

Hate to be picky but let's make a few tiny changes:
1. Change `scrub_repo_url($project->git_repo_url);` to `$git_repo`, and add `$vars['git_repo'] = scrub_repo_url()` to the preprocessor for project nav.  (in theme.inc I believe.)
2. Move the function there too.
3. Check the projects page as well. I can still see the password in the main projects page.

**Comment by jonpugh** [comment]
Merging, thanks!  I'll clean it up...

**Comment by jonpugh** [comment]
hmm needs work. 
obfuscates even when there is no password:

git@github.com:****@github.com:xyz/abc.git

**Comment by llwp** [comment]
not occurring on my local - will investigate further - thanks

**Comment by jonpugh** [comment]
All good now, @llwp 

``` php
function scrub_repo_url($project_git_url){

  $url = parse_url($project_git_url);
  if (isset($url['pass'])) {
    return strtr($project_git_url, array(
      $url['pass'] => '****',
    ));
  }
  else {
    return $project_git_url;
  }
}
```

**Pull request merged**
