### PR TITLE
Devshop cloud

### PR DESCRIPTION
**Pull request by arosboro**
Work on digital ocean to deploy new servers remotely.

### CODE REVIEW

**Comment by jonpugh** [comment]
Like I mentioned on your other PR, I will resume work on devshop_cloud after DrupalCon Barcelona.

Thanks a ton for this! We'll get it in soon.

**Comment by jonpugh** [comment]
@arosboro I've merged this into devshop-cloud so we can get the ball rolling.

I caught an exception when "loading the options":

> PHP Fatal error:  Uncaught exception 'Buzz\Exception\RequestException' with message 'Resolving timed out after 5523 milliseconds' in /var/aegir/devmaster-0.x/profiles/devmaster/modules/devshop/devshop_cloud/providers/digitalocean/digital-ocean-master/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php:29\nStack trace:\n#0 /var/aegir/devmaster-0.x/profiles/devmaster/modules/devshop/devshop_cloud/providers/digitalocean/digital-ocean-master/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(130): Buzz\Client\Curl->send(Object(Buzz\Message\Request), Object(Buzz\Message\Response))\n#1 /var/aegir/devmaster-0.x/profiles/devmaster/modules/devshop/devshop_cloud/providers/digitalocean/digital-ocean-master/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(82): Buzz\Browser->send(Object(Buzz\Message\Request))\n#2 /var/aegir/devmaster-0.x/profiles/devmaster/modules/devshop/devshop_cloud/providers/digitalocean/digital-ocean-master/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(31): Buzz\Browser->call('https://api.dig...', 'GET', Array)\n#3 /var/aegir/de in /var/aegir/devmaster-0.x/profiles/devmaster/modules/devshop/devshop_cloud/providers/digitalocean/digital-ocean-master/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php on line 29, referer: http://devshop.site/admin/devshop/digital_ocean
> 
> ```
> ```

I don't know why it would timeout after such a short time, and I haven't figured it out yet, but I'm so thankful for the work you did.

Let's get this thing moving!

**Comment by arosboro** [comment]
@jonpugh I can get to work on resolving the do issues but I need to start with an nginx branch so we don't have to rebuild our server down the road.  Any suggestions?  How should I go about using the nginx patches until it's merged into devshop:0.x?  I apologize for lack of timeliness resolving branch conflicts, it appears to have been resolved now I am working on travis build errors.

**Comment by jonpugh** [comment]
Thanks, @arosboro ... I'm looking at the NGINX stuff now.  

Let's see if we can get this in this week, even if it's quick and dirty.

**Comment by arosboro** [comment]
Jon after this gets merged I will re-install the official branch and get the cloud code working.  Thanks for finally getting this moving.  Do you predict any issue when migrating from 6.x to 7.x aegir 1.0?

**Comment by jonpugh** [comment]
no, it should be smooth. Aegir 2->3 upgrade works as far as I know, and devshop is a straight port, no DB changes.

The upgrade process uses hostmaster-migrate, so it _should_ work smoothly...

The conversion is actually really close to done, too. Let me know if you want to talk about that!

**Pull request merged**
